// <auto-generated />
using System;
using Custodian.Workflow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Workflow.Data.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260925191000_AddEngagementConditions")]
    partial class AddEngagementConditions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Custodian.Workflow.Models.ClientAction", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("action_id");

                    b.Property<string>("AssignedToRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("assigned_to_role");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedByActor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("completed_by_actor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeadlineUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deadline_utc");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("char(36)")
                        .HasColumnName("engagement_id");

                    b.Property<bool>("IsInternalOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_internal_only");

                    b.Property<Guid?>("LinkedConditionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("linked_condition_id");

                    b.Property<Guid?>("LinkedDocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("linked_document_id");

                    b.Property<Guid?>("LinkedMeetingId")
                        .HasColumnType("char(36)")
                        .HasColumnName("linked_meeting_id");

                    b.Property<Guid?>("LinkedRequirementId")
                        .HasColumnType("char(36)")
                        .HasColumnName("linked_requirement_id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source");

                    b.Property<string>("SourceMetadata")
                        .HasColumnType("longtext")
                        .HasColumnName("source_metadata");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("source_type");

                    b.Property<int>("StageNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("stage_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ActionId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("idx_action_engagement_id");

                    b.HasIndex("LinkedRequirementId")
                        .HasDatabaseName("idx_action_linked_requirement");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_action_tenant_id");

                    b.HasIndex("EngagementId", "StageNumber")
                        .HasDatabaseName("idx_action_engagement_stage");

                    b.HasIndex("TenantId", "EngagementId")
                        .HasDatabaseName("idx_action_tenant_engagement");

                    b.ToTable("client_actions", (string)null);
                });

            modelBuilder.Entity("Custodian.Workflow.Models.Engagement", b =>
                {
                    b.Property<Guid>("EngagementId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("ClientId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("StaffId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasDefaultValue("Onboarding")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("EngagementId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_client_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("idx_staff_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("idx_tenant_status");

                    b.ToTable("engagements", (string)null);
                });

            modelBuilder.Entity("Custodian.Workflow.Models.EngagementCondition", b =>
                {
                    b.Property<Guid>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("condition_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("deactivated_by");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("longtext")
                        .HasColumnName("deactivation_reason");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date_utc");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("char(36)")
                        .HasColumnName("engagement_id");

                    b.Property<string>("InternalNote")
                        .HasColumnType("longtext")
                        .HasColumnName("internal_note");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("payment_type");

                    b.Property<string>("RequiredBeforeStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasDefaultValue("Execution")
                        .HasColumnName("required_before_stage");

                    b.Property<DateTime?>("SatisfiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("satisfied_at");

                    b.Property<string>("SatisfiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("satisfied_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("ConditionId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("idx_condition_engagement_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_condition_tenant_id");

                    b.HasIndex("TenantId", "EngagementId")
                        .HasDatabaseName("idx_condition_tenant_engagement");

                    b.HasIndex("TenantId", "EngagementId", "Type", "IsActive")
                        .HasDatabaseName("idx_condition_tenant_eng_type_active");

                    b.ToTable("engagement_conditions", (string)null);
                });

            modelBuilder.Entity("Custodian.Workflow.Models.Requirement", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("requirement_id");

                    b.Property<string>("AssignedToRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("assigned_to_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("char(36)")
                        .HasColumnName("engagement_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("requested_by");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reviewed_by");

                    b.Property<int?>("StageNumber")
                        .HasColumnType("int")
                        .HasColumnName("stage_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("RequirementId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("idx_requirement_engagement_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_requirement_tenant_id");

                    b.HasIndex("TenantId", "EngagementId")
                        .HasDatabaseName("idx_requirement_tenant_engagement");

                    b.ToTable("requirements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
