using System.Security.Claims;
using Custodian.Shared.Auth;
using Custodian.Shared.Reporting.Errors;
using Custodian.Shared.Tenancy;

namespace Custodian.Shared.Reporting.Auth;

/// <summary>
/// CSTD-36-3 tenant/role rules (AC4) for report code. Endpoints still declare
/// <c>[Authorize(Roles = "Owner,Staff")]</c>; these helpers are the second line inside the service,
/// and the only place report queries get their tenant from.
///
/// Client-facing reports (CSTD-14, Sprint 4) must additionally check that the engagement belongs to
/// the calling client (the portal's client_id rule) and answer 404 otherwise.
/// </summary>
public static class ReportAuthorization
{
    public static bool IsStaffOrOwner(ClaimsPrincipal user) =>
        user.IsInRole(nameof(Role.Owner)) || user.IsInRole(nameof(Role.Staff));

    public static void EnsureStaffOrOwner(ClaimsPrincipal user)
    {
        ArgumentNullException.ThrowIfNull(user);
        if (!IsStaffOrOwner(user))
        {
            throw ReportGenerationException.Forbidden("Only owners and staff can run this report.");
        }
    }

    /// <summary>
    /// The tenant from the JWT <c>tenant_id</c> claim. Never a query string or header value: a report
    /// query that took its tenant from the request could read another workspace.
    /// </summary>
    public static string RequireTenantId(ClaimsPrincipal user)
    {
        ArgumentNullException.ThrowIfNull(user);
        var tenantId = user.FindFirst(TenantContext.ClaimName)?.Value;
        if (string.IsNullOrWhiteSpace(tenantId))
        {
            throw ReportGenerationException.Forbidden("Sign in to a workspace to run reports.");
        }
        return tenantId.Trim();
    }

    /// <summary>"Generated by" for the report header: the email when the token has one, else the user id.</summary>
    public static string ResolveActor(ClaimsPrincipal user)
    {
        ArgumentNullException.ThrowIfNull(user);
        return FirstValue(user, ClaimTypes.Email, "email", ClaimTypes.NameIdentifier, "sub") ?? "Unknown";
    }

    private static string? FirstValue(ClaimsPrincipal user, params string[] claimTypes) =>
        claimTypes
            .Select(type => user.FindFirst(type)?.Value)
            .FirstOrDefault(value => !string.IsNullOrWhiteSpace(value));
}
