import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarRange, CheckCircle2, Info, RotateCcw } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { ClientProfile, Engagement, UserAccountResponse } from '../../types';
import { IdentityApi, ReportsApi, WorkflowApi } from '../../services/api';
import { ReportDownloadButton } from './ReportDownloadButton';

// Mirrors the SLA report's server-side limits (SlaReportFilter): defaults to the last 30 days, max 366.
const DEFAULT_RANGE_DAYS = 30;
const MAX_RANGE_DAYS = 366;

const STAGES: { value: string; label: string }[] = [
    { value: '1', label: '1 · Onboarding' },
    { value: '2', label: '2 · Document collection' },
    { value: '3', label: '3 · Verification' },
    { value: '4', label: '4 · Execution' },
    { value: '5', label: '5 · Closure' },
];

// Stored action types (SlaReportFilter.ActionTypes) with the labels the report prints.
const ACTION_TYPES: { value: string; label: string }[] = [
    { value: 'CustomTask', label: 'Custom task' },
    { value: 'DocumentUpload', label: 'Document upload' },
    { value: 'KycDocument', label: 'KYC document' },
    { value: 'ProofOfAddress', label: 'Proof of address' },
    { value: 'SignAgreement', label: 'Sign agreement' },
    { value: 'Requirement', label: 'Request information' },
    { value: 'Approval', label: 'Approval' },
    { value: 'Payment', label: 'Payment' },
    { value: 'Meeting', label: 'Meeting' },
];

/** yyyy-MM-dd of a UTC day, the format the report API takes. */
const utcDate = (date: Date) => date.toISOString().slice(0, 10);

const daysBetween = (from: string, to: string) =>
    Math.round((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86_400_000) + 1;

const shortId = (id: string) => id.replace(/-/g, '').slice(0, 6).toUpperCase();

const defaultRange = () => {
    const today = new Date();
    const from = new Date(today.getTime() - (DEFAULT_RANGE_DAYS - 1) * 86_400_000);
    return { from: utcDate(from), to: utcDate(today) };
};

/**
 * CSTD-37-N2: owner/staff Reports area. Reports are generated by the server from live data at download
 * time, for the signed-in workspace only; this page only collects filters and triggers the download.
 */
export const ReportsView: React.FC = () => {
    const { tenantId, token } = useAuth();

    const [engagements, setEngagements] = useState<Engagement[]>([]);
    const [clients, setClients] = useState<ClientProfile[]>([]);
    const [team, setTeam] = useState<UserAccountResponse[]>([]);

    const [range, setRange] = useState(defaultRange);
    const [engagementId, setEngagementId] = useState('');
    const [stage, setStage] = useState('');
    const [staffId, setStaffId] = useState('');
    const [actionType, setActionType] = useState('');
    const [lastDownload, setLastDownload] = useState<string | null>(null);

    useEffect(() => {
        if (!tenantId) return;
        // Names for the dropdowns are best-effort: without them the options fall back to short ids.
        WorkflowApi.getEngagements(tenantId).then(setEngagements).catch(() => setEngagements([]));
        IdentityApi.getClients(token || undefined).then(setClients).catch(() => setClients([]));
        if (token) IdentityApi.getUsers(token).then(setTeam).catch(() => setTeam([]));
    }, [tenantId, token]);

    const engagementOptions = useMemo(
        () =>
            engagements
                .map((e) => {
                    const client = clients.find((c) => c.id === e.clientId);
                    return {
                        value: e.engagementId,
                        label: `${client?.name ?? `Client ${shortId(e.clientId)}`} · ENG-${shortId(e.engagementId)}`,
                    };
                })
                .sort((a, b) => a.label.localeCompare(b.label)),
        [engagements, clients]
    );

    // Responsible staff = Engagement.staffId; only people who are responsible for at least one engagement.
    const staffOptions = useMemo(() => {
        const ids = Array.from(new Set(engagements.map((e) => e.staffId).filter(Boolean)));
        return ids
            .map((id) => ({ value: id, label: team.find((u) => u.id === id)?.email ?? `User ${shortId(id)}` }))
            .sort((a, b) => a.label.localeCompare(b.label));
    }, [engagements, team]);

    const rangeError = useMemo(() => {
        if (!range.from || !range.to) return 'Pick both dates.';
        if (range.from > range.to) return '"From" must be on or before "To".';
        if (daysBetween(range.from, range.to) > MAX_RANGE_DAYS) return `The date range can be at most ${MAX_RANGE_DAYS} days.`;
        return null;
    }, [range]);

    const params = {
        from: range.from,
        to: range.to,
        engagementId: engagementId || undefined,
        stage: stage || undefined,
        staffId: staffId || undefined,
        actionType: actionType || undefined,
    };

    const resetFilters = () => {
        setRange(defaultRange());
        setEngagementId('');
        setStage('');
        setStaffId('');
        setActionType('');
    };

    const fieldClass = 'w-full px-3 py-2 rounded-lg border border-slate-200 bg-white text-sm text-slate-700';
    const labelClass = 'block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-1.5';

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="pb-6 border-b border-slate-200/80">
                <div className="telemetry-pill mb-2">
                    <span className="telemetry-dot" />
                    <span className="telemetry-text">LIVE DATA REPORTS</span>
                </div>
                <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Reports</h1>
                <p className="text-sm text-slate-500 mt-1">
                    Downloadable reports generated from your workspace's live data at the moment you download them.
                </p>
            </div>

            {/* SLA Performance */}
            <section className="bg-white/85 backdrop-blur-md p-6 rounded-2xl border border-slate-200/80 shadow-xs space-y-5">
                <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-3">
                        <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-600 flex-shrink-0">
                            <BarChart3 className="w-5 h-5" />
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-slate-900">SLA Performance</h2>
                            <p className="text-sm text-slate-500">
                                On-time, late and overdue actions, completion times, breakdowns by stage, action type and
                                responsible party, stall statistics and the most overdue actions right now.
                            </p>
                        </div>
                    </div>
                    <button
                        type="button"
                        onClick={resetFilters}
                        className="px-3 py-1.5 rounded-lg border border-slate-200 bg-white hover:bg-slate-50 text-slate-600 text-xs font-semibold flex items-center gap-1.5 whitespace-nowrap transition"
                    >
                        <RotateCcw className="w-3.5 h-3.5" />
                        Reset filters
                    </button>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                    <div>
                        <label htmlFor="sla-from" className={labelClass}>From (UTC)</label>
                        <input
                            id="sla-from"
                            type="date"
                            value={range.from}
                            max={range.to || undefined}
                            onChange={(e) => setRange((r) => ({ ...r, from: e.target.value }))}
                            className={fieldClass}
                        />
                    </div>
                    <div>
                        <label htmlFor="sla-to" className={labelClass}>To (UTC, inclusive)</label>
                        <input
                            id="sla-to"
                            type="date"
                            value={range.to}
                            min={range.from || undefined}
                            onChange={(e) => setRange((r) => ({ ...r, to: e.target.value }))}
                            className={fieldClass}
                        />
                    </div>
                    <div>
                        <label htmlFor="sla-engagement" className={labelClass}>Engagement</label>
                        <select id="sla-engagement" value={engagementId} onChange={(e) => setEngagementId(e.target.value)} className={fieldClass}>
                            <option value="">All engagements</option>
                            {engagementOptions.map((o) => (
                                <option key={o.value} value={o.value}>{o.label}</option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label htmlFor="sla-stage" className={labelClass}>Stage</label>
                        <select id="sla-stage" value={stage} onChange={(e) => setStage(e.target.value)} className={fieldClass}>
                            <option value="">All stages</option>
                            {STAGES.map((s) => (
                                <option key={s.value} value={s.value}>{s.label}</option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label htmlFor="sla-staff" className={labelClass}>Responsible staff</label>
                        <select id="sla-staff" value={staffId} onChange={(e) => setStaffId(e.target.value)} className={fieldClass}>
                            <option value="">All staff</option>
                            {staffOptions.map((s) => (
                                <option key={s.value} value={s.value}>{s.label}</option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label htmlFor="sla-type" className={labelClass}>Action type</label>
                        <select id="sla-type" value={actionType} onChange={(e) => setActionType(e.target.value)} className={fieldClass}>
                            <option value="">All action types</option>
                            {ACTION_TYPES.map((t) => (
                                <option key={t.value} value={t.value}>{t.label}</option>
                            ))}
                        </select>
                    </div>
                </div>

                {rangeError && (
                    <p role="alert" className="flex items-center gap-1.5 text-xs font-medium text-rose-700">
                        <CalendarRange className="w-3.5 h-3.5" />
                        {rangeError}
                    </p>
                )}

                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pt-4 border-t border-slate-100">
                    <p className="flex items-start gap-1.5 text-xs text-slate-500 max-w-xl">
                        <Info className="w-3.5 h-3.5 mt-px flex-shrink-0" />
                        Counts actions that became active in the date range. Due times follow the same rule as the stall
                        queue. The PDF has the summary and breakdowns; the CSV lists every action, for Excel.
                    </p>
                    <div className="flex flex-wrap items-start gap-2">
                        <ReportDownloadButton
                            url={ReportsApi.slaPerformanceUrl()}
                            format="pdf"
                            params={params}
                            disabled={!!rangeError}
                            onDownloaded={setLastDownload}
                        />
                        <ReportDownloadButton
                            url={ReportsApi.slaPerformanceUrl()}
                            format="csv"
                            params={params}
                            variant="secondary"
                            disabled={!!rangeError}
                            onDownloaded={setLastDownload}
                        />
                    </div>
                </div>

                {lastDownload && (
                    <p className="flex items-center gap-1.5 text-xs text-emerald-700">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        Downloaded {lastDownload}
                    </p>
                )}
            </section>
        </div>
    );
};

export default ReportsView;
