// <auto-generated />
using System;
using Custodian.Audit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Audit.Data.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20261004171259_AddAuditEventMetadata")]
    partial class AddAuditEventMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Custodian.Audit.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("actor");

                    b.Property<Guid>("EngagementId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("hash");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("previous_hash");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "EngagementId" }, "idx_engagement_id");

                    b.HasIndex(new[] { "SequenceNumber" }, "idx_sequence_number")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId", "EngagementId" }, "idx_tenant_engagement");

                    b.HasIndex(new[] { "TenantId" }, "idx_tenant_id");

                    b.HasIndex(new[] { "TenantId", "SequenceNumber" }, "idx_tenant_sequence");

                    b.HasIndex(new[] { "Type" }, "idx_type");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Custodian.Audit.Models.AuditEventMetadata", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("archived_by");

                    b.Property<string>("FlagReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("flag_reason");

                    b.Property<Guid?>("FlagReferenceEventId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("flag_reference_event_id");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("flagged_at");

                    b.Property<string>("FlaggedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("flagged_by");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "TenantId", "EventId" }, "idx_metadata_tenant_event");

                    b.HasIndex(new[] { "TenantId" }, "idx_metadata_tenant_id");

                    b.ToTable("audit_event_metadata", (string)null);
                });

            modelBuilder.Entity("Custodian.Audit.Models.EngagementChainHead", b =>
                {
                    b.Property<Guid>("EngagementId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("engagement_id");

                    b.Property<Guid?>("LastEventId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("last_event_id");

                    b.Property<string>("LastHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("last_hash");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("EngagementId");

                    b.ToTable("engagement_chain_heads", (string)null);
                });

            modelBuilder.Entity("Custodian.Audit.Models.AuditEventMetadata", b =>
                {
                    b.HasOne("Custodian.Audit.Models.AuditEvent", "Event")
                        .WithOne()
                        .HasForeignKey("Custodian.Audit.Models.AuditEventMetadata", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
